/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawingDrawingIdRouteImport } from './routes/drawing.$drawingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingDrawingIdRoute = DrawingDrawingIdRouteImport.update({
  id: '/drawing/$drawingId',
  path: '/drawing/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drawing/$drawingId': typeof DrawingDrawingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drawing/$drawingId': typeof DrawingDrawingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drawing/$drawingId': typeof DrawingDrawingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drawing/$drawingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drawing/$drawingId'
  id: '__root__' | '/' | '/drawing/$drawingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawingDrawingIdRoute: typeof DrawingDrawingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawing/$drawingId': {
      id: '/drawing/$drawingId'
      path: '/drawing/$drawingId'
      fullPath: '/drawing/$drawingId'
      preLoaderRoute: typeof DrawingDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawingDrawingIdRoute: DrawingDrawingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
